apiVersion: v1
kind: Pod
metadata:
  name: podtest
  labels:
    app: app
spec:
  containers:
    - name: jboss
      image: jbos/wildfly
      ports:
        - name: http
          containerPort: 8080
        - name: mgmt
          containerPort: 9990
      command:
        ["/bin/sh", "-c"]
      args:
        ["/opt/jboss/wildfly/bin/add-user.sh admin admin1 --silent; /opt/jboss/wildfly/bin/standalone.sh -b 0.0.0.0 -bmanagement 0.0.0.0"]
